### ISSUE TITLE
restart a replica or move it from a node to another

### ISSUE THREAD

**Issue by dottgonzo** [redgeoff/couchdb-docker-service#4]
Hi,
i'm trying your docker couchdb cluster solution. I see on github that to scale down i need to move the data from a cluster to another, what happen if a replica restart (maybe moving from a node to another)?

**Comment by redgeoff** [comment]
At this point, moving data between nodes is out of the scope of this project. I suspect that sometime in the future I'll embark on this task, but I have no current plans for this. Of course, a PR would be great, but I'd suggest that a move-to-another-node util be put in it's own repo and then just used by couchdb-docker-service.
