### ISSUE TITLE
Swarm mode problem and discovery

### ISSUE THREAD

**Issue by abrakhim** [redgeoff/couchdb-docker-service#8]
Hi,
there are some problems i faced when trying to get this into production readiness. First, the discovery process does not work. It seems to sometimes register on the first 2 nodes, but on the third node docker-discover-tasks does not even register its own hostname. On the second node it hung after registering its own hostname. So, i removed it from the wrapper.sh and added the hostnames in the containers manually. This triggered cluster setup and all was green. 

Then i tried to simulate a failed node. I started with stopping a container. As swarm spun up a new container, i expected to run the cluster setup again and it would recover. It didn't, as the node was assigned another ip - and no way in swarm service to change that. So, even a short hickup in docker will kill off a node. The first thing to do would be removing this homegrown discovery and rely soley on swarm dns instead of static ips. This would solve the first problem. Will try if that also solves problem 2, the losts cluster state :-)

**Comment by redgeoff** [comment]
I think couchdb-docker-service is a great project for testing apps, but I don't recommend using it for production as:
1. CouchDB isn't really a DB where you can add/remove nodes in an automated fashion. Sure, you can do this, but to properly rebalance the data across nodes requires manual intervention.
2. The swarm mode service creates containers that can be located on any host, which is fine when the there is no data in CouchDB, but after initialization this is a deal-breaker. You can use a network file system to provide virtual access to the files, but in my experience, this adds a 10x performance loss!

This being said, I haven't seen the issues you are talking about with the discovery process. Moreover, I don't think you can rely on swarm mode's DNS as I don't believe it is compatible with CouchDB's addressing. From what I remember, besides IP addresses, CouchDB only really supports short names and I seem to remember that they don't really work over a network. Maybe this has changed.

If you do figure out a better way of discovering nodes then a PR would be very welcome!

**Comment by abrakhim** [comment]
Thanks for your response. I agree that this is not a recommended service to be running in production in a swarm. The statefulness of the clustered couch, some swarm specifics and other little problems make this more complicated than useful. I think couchdb discovery could be done by the underlying distributed erl - if i have some spare time i'll give it a try. Thank you for sharing this service though, i will use a lot of it in the ansible version i am currently putting together as plan b. :-)

**Comment by abrakhim** [comment]
I ended up using your AWS Tutorial without using AWS, dropped swarm and added haproxy, using only 3 docker engines with your container from https://github.com/redgeoff/redgeoff-couchdb-docker. Works like a charm! Thanks again.
